//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSCodePointDataImport.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSCodePointDataImport.Resources.FeatureCodes", typeof(FeatureCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antiquity (non-Roman).
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest / Wood.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        internal static string FM {
            get {
                return ResourceManager.GetString("FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill / Mountain.
        /// </summary>
        internal static string H {
            get {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antiquity (Roman).
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town / Settlement.
        /// </summary>
        internal static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water feature.
        /// </summary>
        internal static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All other features.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
    }
}
